name: Run Tests and Generate Coverage Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm test --coverage=true

      # Upload coverage report to GitHub Pages (optional)
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

      # Publish badge using coverage report (optional)
        - name: Generate badge data from coverage report
          run: |
            bash -c 'coverage report -m | grep -E "^[ ]*Lines:[ ]*([0-9]+)%'" | cut -d ' ' -f 2 > coverage.txt

        - name: Publish coverage badge
          uses: badge/publish@v1
          with:
            value: ${{ fs.readFileSync('coverage.txt') }}
            message: Code Coverage
            color: green
